# Generated by Django 4.2 on 2023-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ("id",)},
        ),
    ]
